config/routes.rb
Rails.application.routes.draw do

  get 'user_has_msg/new/:receiver_id' => "user_has_msg#new", :as => "newmsg"
  post 'user_has_msg/new/:receiver_id' => "message#create"
  get 'user_has_msg/destroy'

  resources :chatrooms
  resources :users, only: [:create]
  resources :room_mems

  get "signup" => "users#signup", :as => "signup"
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  get "home" => "users#home", :as => "home"
  get "home/edit" => "users#edit", :as => "user"
  patch "home/edit" => "users#update"

  get "home/recvmsg/:num" => "user_has_msg#recv", :as => "recvmsg"
  get "home/sendmsg/:num" => "user_has_msg#send2", :as => "sendmsg"

  get "users/:id" => "users#show", :as => "showuser"
  post "users/:id" => "users#add_friend", :as => "addfriend"
  get "chatrooms/enter/:id" => "room_mems#enter", :as => "enterroom"
  post "chatrooms/search/:id" => "application#search", :as => "search_id"
  post "chatrooms/search" => "application#search", :as => "search"
 
  get "chatrooms/settags/:id" => "tag#set", :as => "set_tag"
  post "chatrooms/enter/:id" => "tag#afterset", :as => "after_set_tag"
  get "chatapp/:name" => "chatapp#index", :as => "chatapp"

  root 'homepage#index'

end

app/models/chat_log.rb
class ChatLog < ActiveRecord::Base
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
	has_many :users, :through => :room_mems
	has_many :room_mems
	has_many :tags, :through => :room_tags
	has_many :room_tags
	before_create { generate_room_no(:roomno) }

	def generate_room_no(column)
	  begin
	    self[column] = 1 + Random.rand(9999)
	  end while Chatroom.exists?(column => self[column])
	end

    PRIVACY_TYPES = [['公开', false],['私密', true]]

	validates :roomname, presence: true
	validates :roomcover,  allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: 'must be a URL for GIF, JPG or PNG image.'
	}
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	# 其模型并不存在，所以要给出 :class_name 及 :foreign_key 选项。
	# 以让活动记录知道上哪里去找记录。
	belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"

end

app/models/message.rb
class Message < ActiveRecord::Base
	has_one :user_has_msg
end

app/models/room_mem.rb
class RoomMem < ActiveRecord::Base
	belongs_to :user
	belongs_to :chatroom
end

app/models/room_tag.rb
class RoomTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :chatroom
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :chatrooms, :through => :room_tags
	has_many :room_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :chatrooms, :through => :room_mems
	has_many :room_mems
	has_many :friendships
	has_many :user_has_msgs
	has_many :messages, :through => :user_has_msgs
	# 创建 has_many :through 关联，在 friendships 内找寻 friends。
	has_many :friends, :through => :friendships

	has_secure_password
	before_create { generate_token(:auth_token) }

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end
end

app/models/user_has_msg.rb
class UserHasMsg < ActiveRecord::Base
	belongs_to :message
	belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
	belongs_to :receiver, :class_name => "User", :foreign_key => "receiver_id"
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  
  # GET /chatrooms
  # GET /chatrooms.json
  def index
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @chatroom = Chatroom.find_by_id(params[:id])
    @creater = User.find( @chatroom.user_id )
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.user_id ||= current_user.id

    respond_to do |format|
      if @chatroom.save
        room_mem = RoomMem.new
        room_mem.user_id = current_user.id 
        room_mem.chatroom_id = @chatroom.id
        room_mem.save

        format.html { redirect_to set_tag_path(@chatroom.id) }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
end




  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:roomname, :roomcover, :privacy, :popularity, :memnum, :roomno, :key, :user_id, :description)
    end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
	def set
		@chatroom = Chatroom.find(params[:id])
	end

	def afterset
		@chatroom = Chatroom.find(params[:id])
		tmp = [params[:tag1], params[:tag2], params[:tag3] ]
		tags = Array.new(3)
		for i in 0..2 do

			if Tag.exists?(:tagname => tmp[i])
				tags[i] = Tag.where(:tagname => tmp[i])
			else 
				tags[i] = Tag.new
				tags[i].tagname = tmp[i] 
				tags[i].save
			end
			@chatroom.tags << tags[i]
		end  	
		redirect_to @chatroom
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def signup
		@user = User.new
	end

	def login
		
	end

	def home
		@has_friends = Friendship.where(:user_id => current_user.id)
		@user = current_user
	end

	def show
		if User.exists?(params[:id])
			@user = User.find(params[:id])
		else
			redirect_to :root
		end
	end

	def add_friend
		@user = User.find(params[:id])

		unless Friendship.exists?(:user_id => current_user.id, :friend_id => params[:id])  
			unless Friendship.exists?(:user_id => params[:id], :friend_id => current_user.id)
				unless current_user.id == @user.id
					friendship = Friendship.new
					friendship.user_id = current_user.id
					friendship.friend_id = @user.id
					friendship.save

					friendship1 = Friendship.new
					friendship1.user_id = @user.id 
					friendship1.friend_id = current_user.id
					friendship1.save
				end
			end
		end
		
	end

	def logout
		cookies.delete(:auth_token)
		redirect_to :root
	end

	def create_login_session
		user = User.find_by_username(params[:username])
		if user && user.authenticate(params[:password])
			if params[:remember_me]
				cookies.permanent[:auth_token] = user.auth_token
			else
				cookies[:auth_token] = user.auth_token
			end
			redirect_to :root
		else
			redirect_to :login
		end
	end

	def create
		user = User.new(user_params)
		user.save
		cookies[:auth_token] = user.auth_token
		redirect_to :root
	end

	def edit
	  @user = current_user
	  respond_to { |format| format.html }
	end

	def update
	    @user = current_user
	    if @user.update(info_params)
	    		redirect_to home_path
      	else	
	        format.html { render :edit }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	     
	    end
  	end

	private
	def user_params
		params.require(:user).permit(:username, :password)
	end

	def info_params
		params.require(:user).permit(:phone, :email, :nickname, :gender, :description, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_app_helper.rb
module ChatAppHelper
end

app/helpers/chat_log_helper.rb
module ChatLogHelper
end

app/helpers/chatapp_helper.rb
module ChatappHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/room_mems_helper.rb
module RoomMemsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/user_has_msg_helper.rb
module UserHasMsgHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_chatroom.html.erb
<div class="row">
  <% @chatrooms.each do |chatroom| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(chatroom.roomcover) %>
      <div class="caption">
        <h3><%= chatroom.roomname %></h3>
        <p><%= sanitize(chatroom.description) %></p>
        <div class="home-page-roomtag">
          <% chatroom.tags.each do |tag|  %>
            <span class="label label-info"> <%= link_to tag.tagname, search_id_path(tag.tagname), method: :post %></span>
          <% end %>
        </div>
        <span><li class="fa fa-users"></li> <b><%= chatroom.memnum %></b> Members</span>
        <%= link_to 'JOIN', chatroom %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/chatrooms/_form.html.erb
<%= form_for(@chatroom) do |f| %>
  <% if @chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% @chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "名称" %><br>
    <%= f.text_field :roomname %>
  </div>
  <div class="field">
    <%= f.label "封面url" %><br>
    <%= f.text_field :roomcover %>
  </div>
  <div class="field">
    <%= f.label "描述" %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label "聊天室类型" %><br>
    <%= f.select :privacy, Chatroom::PRIVACY_TYPES, :prompt => "是否公开" %>
  </div>
  <div class="field">
    <%= f.label "密码" %><br>
    <%= f.number_field :key %>
  </div>
  <div class="actions">
    <%= f.submit "创建" %>
  </div>
<% end %>



    

app/views/chatrooms/edit.html.erb
<div class="bs-header">
  <div class="container">
    <h1>编辑聊天室</h1>
  </div>
</div>
<div class="container">
  <div class="content">
    <%= render 'form' %>
  </div>
  <div class="direct_to">
    <%= link_to '返回', :root %>
  </div>
</div>

app/views/chatrooms/list.html.erb
<%= render :partial => "chatroom" %> 

app/views/chatrooms/new.html.erb
<div class="bs-header">
  <div class="container">
    <h1>新建聊天室</h1>
  </div>
</div>
<div class="container">
  <div class="content">
    <%= render 'form' %>
  </div>
  <div class="direct_to">
    <%= link_to '返回', :root %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="bs-header">
  <div class="container">
    <h1> 到时聚聚，聊聊程序</h1>
  </div>
</div>

<div class="container">
    <div class="content">
        <p id="roomname">
          <strong>当前聊天室:</strong>
          <%= @chatroom.roomname %>
          
          <strong>聊天室编号:</strong>
          <%= @chatroom.roomno %>
      </p>
      <p id="describe"> <%= (@chatroom.description) %> </p>

      <div id="img">  <%= image_tag(@chatroom.roomcover) %> </div>

      <p>
        <strong>创建人:</strong>
        <%=  @creater.username %>
        <%= @chatroom.privacy %>
      </p>
      <p>
        <strong>热度:</strong>
        <%= @chatroom.popularity %>
      </p>
      <p>
        <strong>人数:</strong>
        <%= @chatroom.memnum %>
      </p>
    </div>
    <div class="direct_to">
      <td><%= link_to '查看成员列表', room_mem_path %></td> |
      <td><%= link_to '进入聊天室', enterroom_path(@chatroom.id) %></td> |
      <td><%= link_to '返回主页', :root %></td>
    </div>
    
</div>