config/routes.rb
Rails.application.routes.draw do

  get 'user_has_msg/new/:receiver_id' => "user_has_msg#new", :as => "newmsg"
  post 'user_has_msg/new/:receiver_id' => "message#create"
  get 'user_has_msg/destroy'

  resources :chatrooms
  resources :users, only: [:create]
  resources :room_mems

  get "signup" => "users#signup", :as => "signup"
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  get "home" => "users#home", :as => "home"
  get "home/edit" => "users#edit", :as => "user"
  patch "home/edit" => "users#update"

  get "home/recvmsg/:num" => "user_has_msg#recv", :as => "recvmsg"
  get "home/sendmsg/:num" => "user_has_msg#send2", :as => "sendmsg"

  get "users/:id" => "users#show", :as => "showuser"
  post "users/:id" => "users#add_friend", :as => "addfriend"
  get "chatrooms/enter/:id" => "room_mems#enter", :as => "enterroom"
  post "chatrooms/search/:id" => "application#search", :as => "search_id"
  post "chatrooms/search" => "application#search", :as => "search"
 
  get "chatrooms/settags/:id" => "tag#set", :as => "set_tag"
  post "chatrooms/enter/:id" => "tag#afterset", :as => "after_set_tag"
  get "chatapp/:name" => "chatapp#index", :as => "chatapp"

  root 'homepage#index'

end

app/models/chat_log.rb
class ChatLog < ActiveRecord::Base
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
	has_many :users, :through => :room_mems
	has_many :room_mems
	has_many :tags, :through => :room_tags
	has_many :room_tags
	before_create { generate_room_no(:roomno) }

	def generate_room_no(column)
	  begin
	    self[column] = 1 + Random.rand(9999)
	  end while Chatroom.exists?(column => self[column])
	end

    PRIVACY_TYPES = [['公开', false],['私密', true]]

	validates :roomname, presence: true
	validates :roomcover,  allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: 'must be a URL for GIF, JPG or PNG image.'
	}
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	# 其模型并不存在，所以要给出 :class_name 及 :foreign_key 选项。
	# 以让活动记录知道上哪里去找记录。
	belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"

end

app/models/message.rb
class Message < ActiveRecord::Base
	has_one :user_has_msg
end

app/models/room_mem.rb
class RoomMem < ActiveRecord::Base
	belongs_to :user
	belongs_to :chatroom
end

app/models/room_tag.rb
class RoomTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :chatroom
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :chatrooms, :through => :room_tags
	has_many :room_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :chatrooms, :through => :room_mems
	has_many :room_mems
	has_many :friendships
	has_many :user_has_msgs
	has_many :messages, :through => :user_has_msgs
	# 创建 has_many :through 关联，在 friendships 内找寻 friends。
	has_many :friends, :through => :friendships

	has_secure_password
	before_create { generate_token(:auth_token) }

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end
end

app/models/user_has_msg.rb
class UserHasMsg < ActiveRecord::Base
	belongs_to :message
	belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
	belongs_to :receiver, :class_name => "User", :foreign_key => "receiver_id"
end

app/controllers/chatapp_controller.rb
class ChatappController < ApplicationController
	def index
	end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
	def set
		@chatroom = Chatroom.find(params[:id])
	end

	def afterset
		@chatroom = Chatroom.find(params[:id])
		tmp = [params[:tag1], params[:tag2], params[:tag3] ]
		tags = Array.new(3)
		for i in 0..2 do

			if Tag.exists?(:tagname => tmp[i])
				tags[i] = Tag.where(:tagname => tmp[i])
			else 
				tags[i] = Tag.new
				tags[i].tagname = tmp[i] 
				tags[i].save
			end
			@chatroom.tags << tags[i]
		end  	
		redirect_to @chatroom
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def signup
		@user = User.new
	end

	def login
		
	end

	def home
		@has_friends = Friendship.where(:user_id => current_user.id)
		@user = current_user
	end

	def show
		if User.exists?(params[:id])
			@user = User.find(params[:id])
		else
			redirect_to :root
		end
	end

	def add_friend
		@user = User.find(params[:id])

		unless Friendship.exists?(:user_id => current_user.id, :friend_id => params[:id])  
			unless Friendship.exists?(:user_id => params[:id], :friend_id => current_user.id)
				unless current_user.id == @user.id
					friendship = Friendship.new
					friendship.user_id = current_user.id
					friendship.friend_id = @user.id
					friendship.save

					friendship1 = Friendship.new
					friendship1.user_id = @user.id 
					friendship1.friend_id = current_user.id
					friendship1.save
				end
			end
		end
		
	end

	def logout
		cookies.delete(:auth_token)
		redirect_to :root
	end

	def create_login_session
		user = User.find_by_username(params[:username])
		if user && user.authenticate(params[:password])
			if params[:remember_me]
				cookies.permanent[:auth_token] = user.auth_token
			else
				cookies[:auth_token] = user.auth_token
			end
			redirect_to :root
		else
			redirect_to :login
		end
	end

	def create
		user = User.new(user_params)
		user.save
		cookies[:auth_token] = user.auth_token
		redirect_to :root
	end

	def edit
	  @user = current_user
	  respond_to { |format| format.html }
	end

	def update
	    @user = current_user
	    if @user.update(info_params)
	    		redirect_to home_path
      	else	
	        format.html { render :edit }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	     
	    end
  	end

	private
	def user_params
		params.require(:user).permit(:username, :password)
	end

	def info_params
		params.require(:user).permit(:phone, :email, :nickname, :gender, :description, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_app_helper.rb
module ChatAppHelper
end

app/helpers/chat_log_helper.rb
module ChatLogHelper
end

app/helpers/chatapp_helper.rb
module ChatappHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/room_mems_helper.rb
module RoomMemsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/user_has_msg_helper.rb
module UserHasMsgHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tag/_form.html.erb
<div>
  <%= form_tag after_set_tag_path(@chatroom.id) do %>
  <dl>
    <dt> 
      <p>标签 1 </p>
      <%= text_field_tag "tag1", params[:tag1] %>
      <p>标签 2 </p>
      <%= text_field_tag "tag2", params[:tag2] %>
      <p>标签 3 </p>
      <%= text_field_tag "tag3", params[:tag3] %>
      <%= submit_tag "提交",  :class => "login-button btn btn-primary" %> 
    </dt>
  </dl>
  <% end %>
</div>

app/views/tag/set.html.erb
<%= render 'form' %>

app/views/users/add_friend.html.erb
<div class="bs-header">
  <div class="container">
    <h1>
      用户
      <%= @user.username %>
      的个人主页
    </h1>
  </div>
</div>
<div class="container">
  <div class="content">
    <table class="table">
      <thead>
        <tr>
          <th class="name">头像</th>
          <th>成员id</th>
          <th>性别</th>
          <th>手机号</th>
          <th>状态</th>
          <th>最近登录</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
          <tr>  
            <td class="pic"><%= image_tag(@user.avatar) %></td>
            <td><%= @user.username %></td>
            <td><%= @user.gender %></td>
            <td><%= @user.phone %></td>
            <td><%= @user.status %></td>
            <td><%= time_ago_in_words @user.updated_at %></td>
            <td><%= link_to '站内信', newmsg_path(@user.id) %></td>
          </tr>
      </tbody>
    </table>    
  </div>
  <div class="direct_to">
    <td><%= link_to '回到外婆桥', :root %></td>
  </div>
</div>

app/views/users/edit.html.erb
<div class="bs-header">
  <div class="container">
     <h1> 修改信息</h1>
  </div>
</div>
<div class="container">
  <div class="content">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label "手机号" %><br>
        <%= f.text_field :phone %>
      </div>
      <div class="field">
        <%= f.label "邮箱" %><br>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label "昵称" %><br>
        <%= f.text_area :nickname %>
      </div>
      <div class="field">
        <%= f.label "头像" %><br>
        <%= f.text_field :avatar %>
      </div>
      <div class="field">
        <%= f.label "性别" %><br>
        <%= f.select :gender,[['男', 0],['女', 1]], {:selected => 0}%>  
      </div>
      <div class="field">
        <%= f.label "描述" %><br>
        <%= f.text_area :description %>
      </div>
      <div class="actions">
        <%= f.submit "提交" %>
      </div>
    <% end %>    
  </div>
  <div class="direct_to">
    <td><%= link_to '回到外婆桥', :root %></td>
  </div>
</div>

app/views/users/home.html.erb
<%= render :partial => "shared/header" %>
<div class="bs-header">
  <div class="container">
    <h1>好友列表</h1>
  </div>
</div>
<div class="container">
  <div class="content">
     <table class="table table-condensed">
      <thead>
        <tr>
          <th class="name">头像</th>
          <th>id</th>
          <th>状态</th>
          <th>最近登录</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @has_friends.each do |item| %>
          <tr>  
            <td class="pic"><%= image_tag(item.friend.avatar) %></td>
            <td><%= link_to item.friend.username, showuser_path(item.friend.id) %></td>
            <td><%= item.friend.status %></td>
            <td><%= time_ago_in_words item.friend.updated_at %></td>
            <td><%= link_to '站内信', newmsg_path(item.friend.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>   
  </div>
  <div class="direct_to">
    <td><%= link_to '我收到的站内信', recvmsg_path('first') %></td> |
    <td><%= link_to '我发出的站内信', sendmsg_path('first') %></td> |
    <td><%= link_to '修改个人信息', user_path %></td> | 
    <td><%= link_to '回到外婆桥', :root %></td>
  </div>
</div>
<%= render :partial => "shared/footer" %>

app/views/users/login.html.erb
<div>
  <div>
    <%= form_tag "/create_login_session" do %>
    <dl>
      <dt>
        <%= label_tag "用户名" %>
      </dt>
      <dd>
        <%= text_field_tag :username, params[:username] %>
      </dd>
    </dl>
    <dl>
      <dt>
        <%= label_tag "密码" %>
      </dt>
      <dd>
        <%= password_field_tag :password, params[:password] %>
      </dd>
    </dl>
    <dl>
      <%= check_box_tag :remember_me, 1, params[:remember_me] %>
      <%= label_tag :remember_me %>
    </dl>
    <p> <%= submit_tag "登录", :class => "login-button btn btn-primary" %> </p>
    <div>
      <%= link_to "没有账号？注册一个吧", signup_path %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="bs-header">
  <div class="container">
    <h1>
      用户
      <%= @user.username %>
      的个人主页
    </h1>
  </div>
</div>
<div class="container">
  <div class="content">
    <table class="table">
      <thead>
        <tr>
          <th class="name">头像</th>
          <th>成员id</th>
          <th>性别</th>
          <th>手机号</th>
          <th>状态</th>
          <th>最近登录</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
          <tr>  
            <td class="pic"><%= image_tag(@user.avatar) %></td>
            <td><%= @user.username %></td>
            <td><%= @user.gender %></td>
            <td><%= @user.phone %></td>
            <td><%= @user.status %></td>
            <td><%= time_ago_in_words @user.updated_at %></td>
            <td><%= button_to '加为好友', addfriend_path(@user.id), :method => :post %></td>
          </tr>
      </tbody>
    </table>    
  </div>
  <div class="direct_to">
    <td><%= link_to '回到外婆桥', :root %></td>
  </div>
</div>

app/views/users/signup.html.erb
<div class="signup-form-container clearfix">
  <div class="signup-form">
    <%= form_for @user do |f| %>
        <dl class="form">
          <dt><%= f.label :username, "用户名" %></dt>
          <dd><%= f.text_field :username %></dd>
        </dl>
        <dl class="form">
          <dt><%= f.label :password, "密码" %></dt>
          <dd><%= f.password_field :password %></dd>
        </dl>
        <dl class="form">
          <dt><%= f.label :password_confirmation, "请再输入一次" %></dt>
          <dd><%= f.password_field :password_confirmation %></dd>
        </dl>
        <p><%= f.submit "注册", :class => "signup-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>