config/routes.rb
Rails.application.routes.draw do

  get 'user_has_msg/new/:receiver_id' => "user_has_msg#new", :as => "newmsg"
  post 'user_has_msg/new/:receiver_id' => "message#create"
  get 'user_has_msg/destroy'

  resources :chatrooms
  resources :users, only: [:create]
  resources :room_mems

  get "signup" => "users#signup", :as => "signup"
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

  get "home" => "users#home", :as => "home"
  get "home/edit" => "users#edit", :as => "user"
  patch "home/edit" => "users#update"

  get "home/recvmsg/:num" => "user_has_msg#recv", :as => "recvmsg"
  get "home/sendmsg/:num" => "user_has_msg#send2", :as => "sendmsg"

  get "users/:id" => "users#show", :as => "showuser"
  post "users/:id" => "users#add_friend", :as => "addfriend"
  get "chatrooms/enter/:id" => "room_mems#enter", :as => "enterroom"
  post "chatrooms/search/:id" => "application#search", :as => "search_id"
  post "chatrooms/search" => "application#search", :as => "search"
 
  get "chatrooms/settags/:id" => "tag#set", :as => "set_tag"
  post "chatrooms/enter/:id" => "tag#afterset", :as => "after_set_tag"
  get "chatapp/:name" => "chatapp#index", :as => "chatapp"

  root 'homepage#index'

end

app/models/chat_log.rb
class ChatLog < ActiveRecord::Base
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
	has_many :users, :through => :room_mems
	has_many :room_mems
	has_many :tags, :through => :room_tags
	has_many :room_tags
	before_create { generate_room_no(:roomno) }

	def generate_room_no(column)
	  begin
	    self[column] = 1 + Random.rand(9999)
	  end while Chatroom.exists?(column => self[column])
	end

    PRIVACY_TYPES = [['公开', false],['私密', true]]

	validates :roomname, presence: true
	validates :roomcover,  allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: 'must be a URL for GIF, JPG or PNG image.'
	}
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	# 其模型并不存在，所以要给出 :class_name 及 :foreign_key 选项。
	# 以让活动记录知道上哪里去找记录。
	belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"

end

app/models/message.rb
class Message < ActiveRecord::Base
	has_one :user_has_msg
end

app/models/room_mem.rb
class RoomMem < ActiveRecord::Base
	belongs_to :user
	belongs_to :chatroom
end

app/models/room_tag.rb
class RoomTag < ActiveRecord::Base
	belongs_to :tag
	belongs_to :chatroom
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :chatrooms, :through => :room_tags
	has_many :room_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :chatrooms, :through => :room_mems
	has_many :room_mems
	has_many :friendships
	has_many :user_has_msgs
	has_many :messages, :through => :user_has_msgs
	# 创建 has_many :through 关联，在 friendships 内找寻 friends。
	has_many :friends, :through => :friendships

	has_secure_password
	before_create { generate_token(:auth_token) }

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end
end

app/models/user_has_msg.rb
class UserHasMsg < ActiveRecord::Base
	belongs_to :message
	belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
	belongs_to :receiver, :class_name => "User", :foreign_key => "receiver_id"
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
	def set
		@chatroom = Chatroom.find(params[:id])
	end

	def afterset
		@chatroom = Chatroom.find(params[:id])
		tmp = [params[:tag1], params[:tag2], params[:tag3] ]
		tags = Array.new(3)
		for i in 0..2 do

			if Tag.exists?(:tagname => tmp[i])
				tags[i] = Tag.where(:tagname => tmp[i])
			else 
				tags[i] = Tag.new
				tags[i].tagname = tmp[i] 
				tags[i].save
			end
			@chatroom.tags << tags[i]
		end  	
		redirect_to @chatroom
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_app_helper.rb
module ChatAppHelper
end

app/helpers/chat_log_helper.rb
module ChatLogHelper
end

app/helpers/chatapp_helper.rb
module ChatappHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/room_mems_helper.rb
module RoomMemsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloudchat</title>
  <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if params[:controller]=='chatapp' %>
  	<link rel="stylesheet" type="text/css" href="../stylesheets/widgets.css">
  <% end %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">
	<%= yield %>
</body>
</html>

app/views/shared/_banner.html.erb
<div class="home-banner" >
	<div class="container">
		<div>
		<% if current_user %>
			<li><%= link_to current_user.username, home_path %></li>
			<li><%= link_to "logout", logout_path, method: "delete" %></li>
			<% else %>
			<li><%= link_to "login", login_path %></li>
			<li><%= link_to "signup", signup_path %></li>
		<% end %>
		</div>
		<div class="search box">
			<div>
		    <%= form_tag search_id_path do %>
		    <dl>
		      <dt> 
		       	<%= text_field_tag :id, params[:id] %> 
	       	 	<%= submit_tag "搜索",  :class => "login-button btn btn-primary" %> 
		      </dt>
		    </dl>
		    <% end %>
			</div>
		</div>
	</div>
</div>

app/views/shared/_footer.html.erb
<footer id="footer">
  <p>Created and maintained by <a href="https://github.com/FreemanHsu">Andy Hsu</a> and <a href="https://github.com/DeanChensj">Dean Chen</a> .</p>
  <p>Welcome to fork the project.</p>
</footer>

app/views/shared/_header.html.erb
<div>
	<div class="search box">
		<div>
		    <%= form_tag search_path do %>
		    <dl>
		      <dt> 
		       	<%= text_field_tag :id, params[:id] %> 
		   	 	<%= submit_tag "搜索",  :class => "login-button btn btn-primary" %> 
		      </dt>
		    </dl>
		    <% end %>
		</div>
	</div>	
</div>